# Generated by Django 3.2 on 2021-05-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='bookmark',
            new_name='bookmarks',
        ),
    ]
