# Generated by Django 3.2 on 2021-05-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210516_0504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headline',
        ),
        migrations.RemoveField(
            model_name='news',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
    ]
